"use client";
import { useEffect, useMemo, useState } from 'react';
import * as XLSX from 'xlsx';
import { BookOpen, Users, GraduationCap, Megaphone, CreditCard, Upload, Plus, Award, CalendarDays, FileSpreadsheet, Shield, MessageCircle, UserCheck, Search } from 'lucide-react';
import { getDB, saveDB, uid, KEY } from '@/lib/store';
import { Announcement, ClassRoom, DB, Homework, Role, Score, Student } from '@/lib/types';

const roles: {role:Role; title:string; desc:string}[] = [
  {role:'PRINCIPAL', title:'Principal / Super Admin', desc:'Full control of users, reports, fees and school settings'},
  {role:'ADMIN', title:'Admin', desc:'Add students, import Excel, manage enrolment and payments'},
  {role:'TEACHER', title:'Teacher', desc:'Class page, homework, revision, attendance, scores and stamps'},
  {role:'PARENT', title:'Parent', desc:'View homework, progress, announcements and payment status'},
];

function Card({children, className=''}:{children:React.ReactNode;className?:string}){return <div className={`rounded-2xl bg-white p-5 shadow-sm border border-slate-200 ${className}`}>{children}</div>}
function Button({children,onClick,type='button',className=''}:{children:React.ReactNode;onClick?:()=>void;type?:'button'|'submit';className?:string}){return <button type={type} onClick={onClick} className={`rounded-xl px-4 py-2 bg-slate-900 text-white hover:bg-slate-700 transition ${className}`}>{children}</button>}
function Input(props:any){return <input {...props} className={`w-full rounded-xl border border-slate-300 px-3 py-2 ${props.className||''}`} />}
function Select(props:any){return <select {...props} className={`w-full rounded-xl border border-slate-300 px-3 py-2 ${props.className||''}`} />}

export default function Home(){
  const [role,setRole]=useState<Role>('PRINCIPAL');
  const [db,setDb]=useState<DB|null>(null);
  useEffect(()=>{
    let mounted = true;
    const load = async () => {
      const data = await getDB();
      if (mounted) setDb(data);
    };
    load();
    const f = () => {
      const raw = localStorage.getItem(KEY);
      if (raw) setDb(JSON.parse(raw));
    };
    window.addEventListener('school-db-update', f);
    return () => { mounted = false; window.removeEventListener('school-db-update', f); };
  },[]);
  if(!db) return null;
  const update=(next:DB)=>{ setDb(next); saveDB(next).catch((error)=>console.error(error)); };
  return <main className="min-h-screen p-4 md:p-8">
    <div className="mx-auto max-w-7xl space-y-6">
      <header className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
        <div><h1 className="text-3xl md:text-4xl font-bold text-slate-900">School Management Platform</h1><p className="text-slate-600 mt-1">Working local demo for principal, admins, teachers and parents.</p></div>
        <Button onClick={()=>{localStorage.clear(); location.reload()}} className="bg-red-600 hover:bg-red-700">Reset demo data</Button>
      </header>
      <div className="grid md:grid-cols-4 gap-3">{roles.map(r=><button key={r.role} onClick={()=>setRole(r.role)} className={`text-left rounded-2xl p-4 border transition ${role===r.role?'bg-slate-900 text-white border-slate-900':'bg-white border-slate-200 hover:border-slate-400'}`}><div className="font-semibold">{r.title}</div><div className={`text-sm mt-1 ${role===r.role?'text-slate-200':'text-slate-500'}`}>{r.desc}</div></button>)}</div>
      <Stats db={db}/>
      {role==='PRINCIPAL' && <Principal db={db} update={update}/>}      
      {role==='ADMIN' && <Admin db={db} update={update}/>}      
      {role==='TEACHER' && <Teacher db={db} update={update}/>}      
      {role==='PARENT' && <Parent db={db} update={update}/>}      
    </div>
  </main>
}
function Stats({db}:{db:DB}){
  const stats:any[] = [
    ['Students',db.students.length,Users],
    ['Classes',db.classes.length,GraduationCap],
    ['Homework',db.homework.length,BookOpen],
    ['Announcements',db.announcements.length,Megaphone],
    ['Due fees',db.payments.filter(p=>p.status!=='PAID').length,CreditCard],
    ['Enrolments',db.enrollments.length,UserCheck]
  ];
  return <div className="grid grid-cols-2 md:grid-cols-6 gap-3">{stats.map(([label,value,Icon]:any)=><Card key={label}><Icon className="w-5 h-5 text-slate-500"/><div className="text-2xl font-bold mt-2">{value}</div><div className="text-sm text-slate-500">{label}</div></Card>)}</div>
}
function Principal({db,update}:{db:DB;update:(d:DB)=>void}){return <div className="grid lg:grid-cols-3 gap-5"><ManageClasses db={db} update={update}/><Announcements db={db} update={update}/><Payments db={db} update={update}/><Reports db={db}/></div>}
function Admin({db,update}:{db:DB;update:(d:DB)=>void}){return <div className="grid lg:grid-cols-2 gap-5"><AddStudent db={db} update={update}/><ImportExcel db={db} update={update}/><Enrollment db={db} update={update}/><Payments db={db} update={update}/></div>}
function Teacher({db,update}:{db:DB;update:(d:DB)=>void}){const [classId,setClassId]=useState(db.classes[0]?.id||''); const cls=db.classes.find(c=>c.id===classId); const students=db.students.filter(s=>s.classId===classId); return <div className="space-y-5"><Card><div className="flex items-center gap-2 mb-3"><BookOpen/><h2 className="text-xl font-bold">Teacher interactive classroom</h2></div><Select value={classId} onChange={(e:any)=>setClassId(e.target.value)}>{db.classes.map(c=><option key={c.id} value={c.id}>{c.name} - {c.level}</option>)}</Select><p className="text-sm text-slate-500 mt-2">{cls?.schedule} · Teacher: {cls?.teacher}</p></Card><div className="grid lg:grid-cols-2 gap-5"><AddHomework db={db} update={update} classId={classId}/><ScoreStudents db={db} update={update} students={students} classId={classId}/></div><StudentTable db={db}/></div>}
function Parent({db,update}:{db:DB;update:(d:DB)=>void}){const [first,setFirst]=useState('Anas'); const [dob,setDob]=useState('2017-04-10'); const children=db.students.filter(s=>s.firstName.toLowerCase()===first.toLowerCase()&&s.dob===dob); return <div className="space-y-5"><Card><div className="flex items-center gap-2 mb-3"><Search/><h2 className="text-xl font-bold">Parent portal - link child</h2></div><div className="grid md:grid-cols-3 gap-3"><Input placeholder="Child first name" value={first} onChange={(e:any)=>setFirst(e.target.value)}/><Input type="date" value={dob} onChange={(e:any)=>setDob(e.target.value)}/><Button onClick={()=>{}}>Find child</Button></div><p className="text-sm text-slate-500 mt-2">Production version should also use student code or admin approval for security.</p></Card>{children.map(child=><ParentChild key={child.id} child={child} db={db} update={update}/>)}</div>}
function ManageClasses({db,update}:{db:DB;update:(d:DB)=>void}){const [f,setF]=useState({name:'',level:'',teacher:'',schedule:''}); return <Card><h2 className="text-xl font-bold flex gap-2"><GraduationCap/>Classes & levels</h2><form className="space-y-2 mt-4" onSubmit={e=>{e.preventDefault(); update({...db,classes:[...db.classes,{id:uid('c'),...f}] as any}); setF({name:'',level:'',teacher:'',schedule:''})}}><Input placeholder="Class name" value={f.name} onChange={(e:any)=>setF({...f,name:e.target.value})}/><Input placeholder="Level" value={f.level} onChange={(e:any)=>setF({...f,level:e.target.value})}/><Input placeholder="Teacher" value={f.teacher} onChange={(e:any)=>setF({...f,teacher:e.target.value})}/><Input placeholder="Schedule" value={f.schedule} onChange={(e:any)=>setF({...f,schedule:e.target.value})}/><Button type="submit"><Plus className="inline w-4"/> Add class</Button></form><List items={db.classes.map(c=>`${c.name} · ${c.level} · ${c.teacher}`)}/></Card>}
function AddStudent({db,update}:{db:DB;update:(d:DB)=>void}){const [s,setS]=useState<any>({firstName:'',lastName:'',dob:'',level:'Beginner',classId:db.classes[0]?.id,parentName:'',parentEmail:'',balance:0,points:0,stamps:0}); return <Card><h2 className="text-xl font-bold flex gap-2"><Users/>Add student manually</h2><form className="grid md:grid-cols-2 gap-2 mt-4" onSubmit={e=>{e.preventDefault(); update({...db,students:[...db.students,{id:uid('s'),...s,balance:Number(s.balance),points:0,stamps:0}]});}}><Input required placeholder="First name" value={s.firstName} onChange={(e:any)=>setS({...s,firstName:e.target.value})}/><Input required placeholder="Last name" value={s.lastName} onChange={(e:any)=>setS({...s,lastName:e.target.value})}/><Input required type="date" value={s.dob} onChange={(e:any)=>setS({...s,dob:e.target.value})}/><Input placeholder="Level" value={s.level} onChange={(e:any)=>setS({...s,level:e.target.value})}/><Select value={s.classId} onChange={(e:any)=>setS({...s,classId:e.target.value})}>{db.classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</Select><Input placeholder="Parent email" value={s.parentEmail} onChange={(e:any)=>setS({...s,parentEmail:e.target.value})}/><Button type="submit" className="md:col-span-2">Add student</Button></form></Card>}
function ImportExcel({db,update}:{db:DB;update:(d:DB)=>void}){async function read(file:File){const data=await file.arrayBuffer(); const wb=XLSX.read(data); const rows:any[]=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]]); const classId=db.classes[0]?.id||''; const imported=rows.map(r=>({id:uid('s'),firstName:r.firstName||r.FirstName||r['First Name']||'',lastName:r.lastName||r.LastName||r['Last Name']||'',dob:r.dob||r.DOB||'',level:r.level||r.Level||'Beginner',classId,parentName:r.parentName||'',parentEmail:r.parentEmail||'',balance:Number(r.balance||0),points:0,stamps:0})).filter(x=>x.firstName); update({...db,students:[...db.students,...imported]}); alert(`Imported ${imported.length} students`)} return <Card><h2 className="text-xl font-bold flex gap-2"><FileSpreadsheet/>Excel import</h2><p className="text-sm text-slate-500 my-3">Upload .xlsx with columns: firstName, lastName, dob, level, parentEmail, balance.</p><Input type="file" accept=".xlsx,.xls,.csv" onChange={(e:any)=>e.target.files?.[0]&&read(e.target.files[0])}/></Card>}
function AddHomework({db,update,classId}:{db:DB;update:(d:DB)=>void;classId:string}){const [h,setH]=useState({title:'',revision:'',date:new Date().toISOString().slice(0,10),dueDate:''}); return <Card><h2 className="text-xl font-bold flex gap-2"><CalendarDays/>Homework & revision</h2><form className="space-y-2 mt-4" onSubmit={e=>{e.preventDefault(); update({...db,homework:[...db.homework,{id:uid('h'),classId,teacher:'Current teacher',...h}]});}}><Input placeholder="Homework title" value={h.title} onChange={(e:any)=>setH({...h,title:e.target.value})}/><textarea className="w-full rounded-xl border border-slate-300 px-3 py-2" placeholder="Revision / notes" value={h.revision} onChange={(e:any)=>setH({...h,revision:e.target.value})}/><Input type="date" value={h.date} onChange={(e:any)=>setH({...h,date:e.target.value})}/><Input type="date" value={h.dueDate} onChange={(e:any)=>setH({...h,dueDate:e.target.value})}/><Button type="submit">Publish homework</Button></form></Card>}
function ScoreStudents({db,update,students,classId}:{db:DB;update:(d:DB)=>void;students:Student[];classId:string}){const add=(studentId:string)=>{const score=Number(prompt('Score out of 10','8')||0); const points=Number(prompt('Points to add','1')||0); const stamps=Number(prompt('Stamps to add','1')||0); update({...db,students:db.students.map(s=>s.id===studentId?{...s,points:s.points+points,stamps:s.stamps+stamps}:s),scores:[...db.scores,{id:uid('sc'),studentId,classId,date:new Date().toISOString().slice(0,10),score,points,stamps,notes:'Class participation'}]})}; return <Card><h2 className="text-xl font-bold flex gap-2"><Award/>Scores, points & stamps</h2><div className="space-y-2 mt-4">{students.map(s=><div key={s.id} className="flex items-center justify-between rounded-xl border p-3"><div><b>{s.firstName} {s.lastName}</b><div className="text-sm text-slate-500">{s.points} points · {s.stamps} stamps</div></div><Button onClick={()=>add(s.id)}>Add result</Button></div>)}</div></Card>}
function Announcements({db,update}:{db:DB;update:(d:DB)=>void}){const [a,setA]=useState<any>({title:'',body:'',audience:'ALL'}); return <Card><h2 className="text-xl font-bold flex gap-2"><Megaphone/>Announcements</h2><form className="space-y-2 mt-4" onSubmit={e=>{e.preventDefault(); update({...db,announcements:[{id:uid('a'),date:new Date().toISOString().slice(0,10),...a},...db.announcements]});}}><Input placeholder="Title" value={a.title} onChange={(e:any)=>setA({...a,title:e.target.value})}/><textarea className="w-full rounded-xl border border-slate-300 px-3 py-2" placeholder="Message" value={a.body} onChange={(e:any)=>setA({...a,body:e.target.value})}/><Select value={a.audience} onChange={(e:any)=>setA({...a,audience:e.target.value})}><option>ALL</option><option>PARENTS</option><option>STUDENTS</option><option>TEACHERS</option></Select><Button type="submit">Send announcement</Button></form><List items={db.announcements.map(a=>`${a.date}: ${a.title}`)}/></Card>}
function Payments({db,update}:{db:DB;update:(d:DB)=>void}){return <Card><h2 className="text-xl font-bold flex gap-2"><CreditCard/>Payments</h2><div className="space-y-2 mt-4">{db.payments.map(p=>{const s=db.students.find(x=>x.id===p.studentId);return <div key={p.id} className="rounded-xl border p-3"><div className="flex justify-between"><b>{s?.firstName} {s?.lastName}</b><span className="text-sm">${p.amount} · {p.status}</span></div><div className="text-sm text-slate-500">Due: {p.dueDate} · {p.note}</div><div className="flex gap-2 mt-2"><Button className="bg-green-700" onClick={()=>update({...db,payments:db.payments.map(x=>x.id===p.id?{...x,status:'PAID'}:x)})}>Mark paid</Button><Button className="bg-amber-600" onClick={()=>alert('Reminder sent in production by email/SMS')}>Remind parent</Button></div></div>})}</div></Card>}
function Enrollment({db,update}:{db:DB;update:(d:DB)=>void}){const [e,setE]=useState({firstName:'',lastName:'',dob:'',parentName:'',parentEmail:'',level:'Beginner'}); return <Card><h2 className="text-xl font-bold flex gap-2"><Shield/>Public enrolment link</h2><p className="text-sm text-slate-500 mt-2">Share this route in production: /enrol/register-school-code</p><form className="grid md:grid-cols-2 gap-2 mt-4" onSubmit={ev=>{ev.preventDefault(); update({...db,enrollments:[...db.enrollments,{id:uid('en'),status:'NEW',...e}]});}}>{Object.keys(e).map(k=><Input key={k} placeholder={k} value={(e as any)[k]} onChange={(ev:any)=>setE({...e,[k]:ev.target.value})}/>) }<Button type="submit" className="md:col-span-2">Submit enrolment request</Button></form><List items={db.enrollments.map(x=>`${x.firstName} ${x.lastName} · ${x.status}`)}/></Card>}
function ParentChild({child,db,update}:{child:Student;db:DB;update:(d:DB)=>void}){const hw=db.homework.filter(h=>h.classId===child.classId); const scores=db.scores.filter(s=>s.studentId===child.id); const payments=db.payments.filter(p=>p.studentId===child.id); return <div className="grid lg:grid-cols-3 gap-5"><Card><h2 className="text-xl font-bold">{child.firstName}'s progress</h2><p className="mt-2">Points: <b>{child.points}</b></p><p>Stamps: <b>{child.stamps}</b></p><List items={scores.map(s=>`${s.date}: score ${s.score}/10, +${s.points} points, +${s.stamps} stamps`)}/></Card><Card><h2 className="text-xl font-bold">Homework</h2><List items={hw.map(h=>`${h.dueDate}: ${h.title} - ${h.revision}`)}/></Card><Card><h2 className="text-xl font-bold">Payments & receipts</h2>{payments.map(p=><div key={p.id} className="border rounded-xl p-3 mt-2"><b>${p.amount}</b> · {p.status}<Input type="file" className="mt-2" onChange={(e:any)=>{const name=e.target.files?.[0]?.name; update({...db,payments:db.payments.map(x=>x.id===p.id?{...x,status:'PENDING_REVIEW',receiptName:name}:x)})}}/><p className="text-sm text-slate-500">Upload receipt for admin review.</p></div>)}</Card><Card className="lg:col-span-3"><h2 className="text-xl font-bold flex gap-2"><MessageCircle/>Announcements</h2><List items={db.announcements.map(a=>`${a.date}: ${a.title} - ${a.body}`)}/></Card></div>}
function Reports({db}:{db:DB}){const totalDue=db.payments.filter(p=>p.status!=='PAID').reduce((a,b)=>a+b.amount,0); return <Card className="lg:col-span-3"><h2 className="text-xl font-bold">Principal dashboard</h2><div className="grid md:grid-cols-4 gap-3 mt-4"><div className="rounded-xl bg-slate-100 p-4">Total unpaid<br/><b>${totalDue}</b></div><div className="rounded-xl bg-slate-100 p-4">Avg points<br/><b>{Math.round(db.students.reduce((a,b)=>a+b.points,0)/Math.max(1,db.students.length))}</b></div><div className="rounded-xl bg-slate-100 p-4">Teacher activity<br/><b>{db.homework.length} posts</b></div><div className="rounded-xl bg-slate-100 p-4">New enrolments<br/><b>{db.enrollments.filter(e=>e.status==='NEW').length}</b></div></div></Card>}
function StudentTable({db}:{db:DB}){return <Card><h2 className="text-xl font-bold">All students</h2><div className="overflow-auto mt-4"><table className="w-full text-sm"><thead><tr className="text-left border-b"><th>Name</th><th>DOB</th><th>Class</th><th>Points</th><th>Stamps</th><th>Balance</th></tr></thead><tbody>{db.students.map(s=><tr key={s.id} className="border-b"><td>{s.firstName} {s.lastName}</td><td>{s.dob}</td><td>{db.classes.find(c=>c.id===s.classId)?.name}</td><td>{s.points}</td><td>{s.stamps}</td><td>${s.balance}</td></tr>)}</tbody></table></div></Card>}
function List({items}:{items:string[]}){return <ul className="mt-3 space-y-1 text-sm text-slate-600">{items.slice(0,8).map((x,i)=><li key={i} className="border-b last:border-b-0 py-1">{x}</li>)}</ul>}
